import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

import AppProvider from "./redux/provider";
import MainLayout from "@/layout/MainLayout";
import ToastProvider from "./components/ToastProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <MainLayout>
            <Header />
            <main className="min-h-svh"> {children}</main>
            <footer>this is footer</footer>
            <ToastProvider />
          </MainLayout>
        </AppProvider>
      </body>
    </html>
  );
}
